Logic app
Egor-Slatvinskiy-idf/guessing_game pull request #1
Opened 2022-08-19 20:35 UTC by Egor-Slatvinskiy-idf

2022-08-22 10:49 UTC, vladimir-hodaryonok-idf commented on packages/domain/lib/usecase/check_usecase.dart
> +import '../entity/number.dart';
use package import

2022-08-22 10:49 UTC, vladimir-hodaryonok-idf commented on lib/main.dart
> +      debugShowCheckedModeBanner: false,
On my opinion, better to move MyApp widget in to presentation package

2022-08-22 10:49 UTC, vladimir-hodaryonok-idf commented on packages/domain/lib/usecase/check_usecase.dart
> +import '../entity/number.dart';
better to use package import

2022-08-22 10:49 UTC, vladimir-hodaryonok-idf commented on packages/domain/lib/usecase/generate_usecase.dart
> +    final randomNum = Random().nextInt(3).toString();
3 magic number

2022-08-22 10:49 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/bloc/bloc.dart
> +  final _checkUseCase = CheckNumUseCase();
better to pass use Cases into constractor

2022-08-22 10:49 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/bloc/bloc.dart
> +import 'package:domain/entity/number.dart';
warning: Depend on referenced packages

2022-08-22 10:49 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/bloc/bloc.dart
> +  late int _counter;
On my opinion, using late is no good practice.

2022-08-22 10:49 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/bloc/bloc.dart
> +    _randomNum = GenerateNumUseCase().call();
same, inject use case in to constractor

2022-08-22 10:49 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/bloc/bloc.dart
> +      _counter--;
decrementation should be in use case

2022-08-22 10:49 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/bloc/bloc_state.dart
> +  final String rNumber;
what is 'r' in this name?

2022-08-22 10:49 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/ui/home_page/home_widget.dart
> +            if(state.counter == 0 && state is !GuessedSuccessState) ...[
magic number

2022-08-22 11:14 UTC, elizaveta-seleznyova-idf commented on lib/main.dart
> +      debugShowCheckedModeBanner: false,
Agreed with Vladimir

2022-08-22 11:16 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/bloc/bloc.dart
> +  final _checkUseCase = CheckNumUseCase();
disagree, since we are not using 'di container' at the moment, we would need to declare it in the ui constructor

2022-08-22 11:18 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/bloc/bloc.dart
> +  late int _counter;
I love 'late' variables

2022-08-22 11:21 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/bloc/bloc.dart
> +    _randomNum = GenerateNumUseCase().call();
drawn from the comment about assigning a constructor variable

2022-08-22 11:22 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/bloc/bloc_state.dart
> +  final String rNumber;
corrected!

2022-08-22 11:22 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/ui/home_page/home_widget.dart
> +            if(state.counter == 0 && state is !GuessedSuccessState) ...[
corrected!

2022-08-22 11:22 UTC, Egor-Slatvinskiy-idf commented on packages/domain/lib/usecase/check_usecase.dart
> +import '../entity/number.dart';
corrected!

2022-08-22 11:22 UTC, Egor-Slatvinskiy-idf commented on lib/main.dart
> +      debugShowCheckedModeBanner: false,
corrected!

2022-08-22 11:22 UTC, Egor-Slatvinskiy-idf commented on packages/domain/lib/usecase/check_usecase.dart
> +import '../entity/number.dart';
corrected!

2022-08-22 11:23 UTC, Egor-Slatvinskiy-idf commented on packages/domain/lib/usecase/generate_usecase.dart
> +    final randomNum = Random().nextInt(3).toString();
corrected!

2022-08-22 11:25 UTC, elizaveta-seleznyova-idf commented on packages/domain/pubspec.yaml
> +homepage:
Do u need it here?

2022-08-22 11:25 UTC, elizaveta-seleznyova-idf commented on packages/presentation/pubspec.yaml
> +homepage:
Do u need homepage here?

2022-08-22 11:30 UTC, elizaveta-seleznyova-idf commented on packages/presentation/lib/ui/home_page/home_widget.dart
> +                _TextFieldWidget(),
Maybe better to add to separate widgets? In other files?

2022-08-22 11:34 UTC, elizaveta-seleznyova-idf commented on packages/presentation/lib/ui/home_page/home_widget.dart
> +          children: [
For better readability better to add AppBar with some text like "Guessing game" or just add SizeBox().

2022-08-22 11:36 UTC, elizaveta-seleznyova-idf commented on packages/presentation/lib/ui/home_page/home_widget.dart
> +      children: const [
Maybe will be better to move these hints closer to buttons?

2022-08-22 11:37 UTC, elizaveta-seleznyova-idf commented on packages/presentation/lib/ui/home_page/home_widget.dart
> +      children: const [
(just for better readability)

2022-08-22 11:45 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/ui/home_page/home_widget.dart
> +                _TextFieldWidget(),
I do not see the point in this, since the file is small

2022-08-22 11:47 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/ui/home_page/home_widget.dart
> +          children: [
"appbar" is definitely redundant in my opinion in this app

2022-08-22 11:52 UTC, Egor-Slatvinskiy-idf commented on packages/domain/pubspec.yaml
> +homepage:
hmmm... I don't see it in my project.

2022-08-22 11:52 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/pubspec.yaml
> +homepage:
hmmm... I don't see it in my project.

2022-08-22 11:54 UTC, Egor-Slatvinskiy-idf commented on packages/domain/pubspec.yaml
> +homepage:
corrected!

2022-08-22 11:54 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/pubspec.yaml
> +homepage:
corrected!

2022-08-23 11:56 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/bloc/bloc.dart
> +  final _checkUseCase = CheckNumUseCase();
@sergei-mikhailovskii-idf

2022-08-23 11:57 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/bloc/bloc.dart
> +  late int _counter;
@sergei-mikhailovskii-idf

2022-08-23 12:15 UTC, vladimir-hodaryonok-idf approved these changes

2022-08-23 14:35 UTC, elizaveta-seleznyova-idf approved these changes

2022-08-23 15:06 UTC, vladimir-hodaryonok-idf approved these changes

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf requested changes

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on packages/domain/pubspec.yaml
> +# For information on the generic Dart part of this file, see the
cleanup - remove redundant comments

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/bloc/bloc.dart
> +  final _checkUseCase = CheckNumUseCase();
agree with @vladimir-hodaryonok-idf . now it's ok, that we will have a big chains to create bloc in widget. but we are still following di pattern in this case. in future we will get bloc from container and big chains will be removed

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/bloc/bloc.dart
> +  late int _counter;
agree with @elizaveta-seleznyova-idf and @vladimir-hodaryonok-idf 
reference for the Android, but the logic is same in Flutter too

https://www.youtube.com/watch?v=0nXXUzMyF8c

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/bloc/bloc.dart
> +          GuessedInitialState(randomNum: '', counter: _counter),
(optional) create separate constructor of factory method to create default state

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/bloc/bloc.dart
> +  late bool _isGuessed;
remove late

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/bloc/bloc.dart
> +      GuessedRefreshEvent event, Emitter<GuessedState> emit) {
add comma after emit for formatting

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/bloc/bloc.dart
> +    _randomNum = GenerateNumUseCase().call();
-//-

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/bloc/bloc.dart
> +      GuessedStartEvent event, Emitter<GuessedState> emit) {
formatting

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/bloc/bloc.dart
> +      GuessedCheckEvent event, Emitter<GuessedState> emit) {
-//-

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/bloc/bloc.dart
> +    if (compare) {
naming - it should be named not compare, but smth like `isGuessSuccess`

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/bloc/bloc.dart
> +      _counter--;
up to u, in this implementation it is ok (imho)

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/ui/home_page/home_widget.dart
> +          children: [
up to u, it is not very important

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/ui/home_page/home_widget.dart
> +                _TextFieldWidget(),
agree with @Egor-Slatvinskiy-idf

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/ui/home_page/home_widget.dart
> +                if (state.isGuessed == true) ...[
strange logic - if state is GuessedSuccessState, how isGuessed can be false. I think variable isGuessed is redundant in this state

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/ui/home_page/home_widget.dart
> +                if (state.isGuessed == false) ...[
-//-

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/ui/home_page/home_widget.dart
> +            if (state is GuessedInitialState) ...[
bad idea to create a button for each state. create 2 buttons. icon will contain a condition - yes, because it depends on state, but click logic should be in bloc

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/ui/home_page/home_widget.dart
> +      children: const [
it's ok

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on packages/presentation/pubspec.yaml
> +# For information on the generic Dart part of this file, see the
cleanup - comments

2022-08-23 17:05 UTC, sergei-mikhailovskii-idf commented on pubspec.lock
>        url: "https://pub.dartlang.org"
ignore the file and delete it

2022-08-23 21:39 UTC, Egor-Slatvinskiy-idf commented on packages/domain/pubspec.yaml
> +# For information on the generic Dart part of this file, see the
corrected!

2022-08-23 21:39 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/bloc/bloc.dart
> +  late bool _isGuessed;
corrected!

2022-08-23 21:40 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/bloc/bloc.dart
> +      GuessedRefreshEvent event, Emitter<GuessedState> emit) {
corrected!

2022-08-23 21:41 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/bloc/bloc.dart
> +      GuessedStartEvent event, Emitter<GuessedState> emit) {
corrected!

2022-08-23 21:41 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/bloc/bloc.dart
> +      GuessedCheckEvent event, Emitter<GuessedState> emit) {
corrected!

2022-08-23 21:41 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/bloc/bloc.dart
> +    if (compare) {
corrected!

2022-08-23 21:42 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/ui/home_page/home_widget.dart
> +                if (state.isGuessed == true) ...[
corrected!

2022-08-23 21:42 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/ui/home_page/home_widget.dart
> +                if (state.isGuessed == false) ...[
corrected!

2022-08-23 21:42 UTC, Egor-Slatvinskiy-idf commented on pubspec.lock
>        url: "https://pub.dartlang.org"
corrected!

2022-08-23 21:43 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/pubspec.yaml
> +# For information on the generic Dart part of this file, see the
corrected!

2022-08-24 13:23 UTC, elizaveta-seleznyova-idf approved these changes

2022-08-24 15:15 UTC, alexei-kruk-idf approved these changes

2022-08-24 15:15 UTC, alexei-kruk-idf commented on packages/domain/lib/use_case/generate_use_case.dart
> +  }
you can write it in method call()

2022-08-24 15:54 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/check_usecase.dart
> +import '../entity/number.dart';
interesting moment - dart guidelines say that it's better to use relative imports for the files from same package instead of full path

https://dart.dev/guides/language/effective-dart/usage#prefer-relative-import-paths

but I also like package imports more. so it's up to u

2022-08-24 15:56 UTC, sergei-mikhailovskii-idf approved these changes

2022-08-24 17:49 UTC, merged