implementation of self-written Cubit
Egor-Slatvinskiy-idf/guessing_game pull request #2
Opened 2022-08-25 17:12 UTC by Egor-Slatvinskiy-idf

2022-08-27 12:47 UTC, vladimir-hodaryonok-idf approved these changes
do not forget to delete from project unused dirs like bloc and ui

2022-08-27 12:47 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/new_bloc/bloc/main_tile.dart
> +  MainState state;
on my opinion state must be immutable (final fields)

2022-08-27 12:47 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/new_bloc/bloc/main_bloc.dart
> +      handleData(state: MainState.success, counter: --copyCounter, randomNum: randomNum);
you store in bloc your _tile, which contains not final fields like counter and randomNum, you can use this fields and mutate them (I don't like this approach), and then use "_updateData(_tile)" method. But "updateData" method in this case should be reworked and redundant variables removed.

2022-08-27 12:47 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/new_bloc/bloc/main_bloc.dart
> +  void guessedRestart() {
here you generate "randomNum" by useCase, then call "_updateData" where you again generate "randomNum"

2022-08-27 12:47 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/new_bloc/bloc/main_tile.dart
> +        '',
what is it?

2022-08-27 12:47 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/new_bloc/new_ui/main_screen.dart
> +          onPressed: tile.state == MainState.success ||
I have some thoughts about Sergey's notation (about moving onClick method in to bloc). you can try to create in block something like this:
Function()? onClick(bool predicate) => predicate ? () {
    //todo do something
  } : null;
but I do not checked this. you can try by yourself)

2022-08-27 12:47 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/ui/home_page/home_widget.dart
>    Widget build(BuildContext context) {
delete old files from project

2022-08-27 12:47 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/new_bloc/bloc/main_bloc.dart
> +  String? randomNum;
you can try to make it lazy 
lazy String randomNum = _generateUseCase();
or try smth. else , or think about opportunity to avoid to create this variable
After that you do not need nullable field "String randomNumber;" in your Num class

2022-08-27 12:47 UTC, vladimir-hodaryonok-idf commented on packages/domain/lib/entity/number.dart
> +  final String? randomNum;
no needed nullable

2022-08-27 14:54 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/new_bloc/bloc/main_tile.dart
> +  MainState state;
this will result in late being applied, due to the updateParams method

2022-08-27 15:03 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/new_bloc/bloc/main_bloc.dart
> +  void guessedRestart() {
method "guessedRestart" is used to generate a new number and update counter, "updateDate" is used to initialize

2022-08-27 15:09 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/new_bloc/new_ui/main_screen.dart
> +          onPressed: tile.state == MainState.success ||
looked all over the Internet, it turns out only in "onPressed" method to pass null, but button is not blocked on the UI

2022-08-27 15:13 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/new_bloc/bloc/main_bloc.dart
> +  void guessedRestart() {
randomNum = _generateUseCase(); stroke 56
then  _updateData(_tile); 
and again
randomNum = _generateUseCase(); stroke 45

2022-08-27 15:20 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/new_bloc/bloc/main_bloc.dart
> +  void guessedRestart() {
that's right, if I change it to late String randomNum = GenerateUseCase(); then generation of a new number will also take place in guessedCheckNum method

2022-08-27 15:24 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/new_bloc/bloc/main_bloc.dart
> +  String? randomNum;
bad use of late

2022-08-27 15:26 UTC, Egor-Slatvinskiy-idf commented on packages/domain/lib/entity/number.dart
> +  final String? randomNum;
will result in unnecessary addition to the constructor and creation of a getter

2022-08-29 13:00 UTC, elizaveta-seleznyova-idf approved these changes

2022-08-29 14:06 UTC, alexei-kruk-idf approved these changes

2022-08-29 14:06 UTC, alexei-kruk-idf commented on packages/domain/lib/entity/number.dart
>  class Num {
it's better to rename it, because it's reserved word

2022-08-29 14:06 UTC, alexei-kruk-idf commented on packages/presentation/lib/new_cubit/base_cubit/cubit.dart
> +  final _cubitTile = MainTile.init();
for base bloc create other tile and use her(you can look factorial project)

2022-08-29 14:06 UTC, alexei-kruk-idf commented on packages/presentation/lib/new_cubit/cubit/main_cubit.dart
> +  String? randomNum;
move to tile

2022-08-29 14:06 UTC, alexei-kruk-idf commented on packages/presentation/lib/new_cubit/cubit/main_cubit.dart
> +    }
you can write:
final state = isGuessSuccess ? MainState.success : MainState.failure
handleData(
        state: state,
        counter: --copyCounter,
        randomNum: randomNum,
      );

2022-08-29 14:06 UTC, alexei-kruk-idf commented on packages/presentation/lib/ui/home_widget/home_widget.dart
> +        style: const TextStyle(color: Colors.black, fontSize: 24, height: 2),
comma

2022-08-29 14:06 UTC, alexei-kruk-idf commented on packages/presentation/lib/ui/home_widget/home_widget.dart
> +              style: TextStyle(fontSize: 16, color: Colors.blue),
check commas in file :)

2022-08-29 15:03 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/new_cubit/cubit/main_cubit.dart
> +  String? randomNum;
in tile it is, this variable is for assignment and so that generateUseCase is not called again

2022-08-29 15:06 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/new_cubit/cubit/main_cubit.dart
> +    }
in my humble opinion, more readable, like mine, correct me if I'm wrong)

2022-08-29 15:55 UTC, Egor-Slatvinskiy-idf commented on packages/presentation/lib/new_cubit/base_cubit/cubit.dart
> +  final _cubitTile = MainTile.init();
in private messages

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf requested changes

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf commented on lib/di/impl_dependency.dart
> +}
(naming) - impl -> init, dependency -> dependencies

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf commented on lib/main.dart
> +import 'package:untitled1/di/impl_dependency.dart';
what's a strange module name?

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/entity/game_numbers.dart
> +class GameNumbers {
(naming) GameNumbers says about nothing actually

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/entity/model_guessed_game.dart
> +class Model {
(naming) same as higher

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/new_cubit/base_cubit/cubit_screen.dart
> +abstract class CubitScreen extends StatefulWidget {
no need in this class

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/new_cubit/cubit/main_cubit.dart
> +  String? randomNum;
agree with @alexei-kruk-idf. it relates to the state. same as copyCounter (also need to be renamed)

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/new_cubit/cubit/main_cubit.dart
> +    _updateData(_tile);
no need to pass tile as param as it is class-level variable. u have an access to it in _updateData method

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/new_cubit/cubit/main_cubit.dart
> +    MainTile data,
-//-

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/new_cubit/cubit/main_cubit.dart
> +    copyCounter = data.counter;
why _updateData has other logic besides sending event to stream?

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/new_cubit/cubit/main_cubit.dart
> +      randomNum: randomNum,
this fields should be encapsulated

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/new_cubit/cubit/main_cubit.dart
> +    }
up to u. I prefer @alexei-kruk-idf approach. because if we should pass 100 params to the method it will bring us a lot of duplicated code. but in this case it's ok

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/new_cubit/cubit/main_cubit.dart
> +  TextEditingController get textController => _textController;
move it higher, to variables declaration

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/new_cubit/cubit/main_tile.dart
> +  String randomNum;
make them final

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/ui/home_widget/home_widget.dart
> +                      tile.state != MainState.success
create method in tile which will encapsulate this condition

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/ui/home_widget/home_widget.dart
> +                  tile.state == MainState.failure && tile.counter > 0
-//-

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf commented on packages/presentation/pubspec.yaml
> +  get_it: ^7.2.0
u don't need it here. u should place it in domain

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf commented on pubspec.yaml
> +  get_it: ^7.2.0
u don't need it here

2022-08-29 18:49 UTC, sergei-mikhailovskii-idf commented on pubspec.yaml
> +    path: packages/domain
presentation already contains domain

2022-08-30 17:15 UTC, vladimir-hodaryonok-idf approved these changes

2022-08-30 17:15 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/new_cubit/base_cubit/cubit.dart
> +  void handleData({D? tile}) {
is D can be null in your bloc?

2022-08-30 17:15 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/new_cubit/cubit/main_cubit.dart
> +    _tile = MainTile.init();
u can use here _tile = _tile.copyWith( ....,   ... , _generateUseCase());

2022-08-30 17:15 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/new_cubit/cubit/main_tile.dart
> +        counter: 3,
magic

2022-08-31 07:35 UTC, sergei-mikhailovskii-idf requested changes

2022-08-31 07:35 UTC, sergei-mikhailovskii-idf commented on lib/di/injects_dependency.dart
> +  injectsDependencyPresentation();
<img width="997" alt="image" src="https://user-images.githubusercontent.com/64923802/187619083-9e0d6d3d-d0a5-4641-a7e1-e7281e283868.png">

but this methods main aim is not to inject dependencies but to add them to container  need to rename

откройте окно, душнила залетел в ревью пров

2022-08-31 07:35 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/entity/copy_numbers.dart
> +class CopyNumbers {
still problems with naming. what is this class need for?

2022-08-31 15:38 UTC, sergei-mikhailovskii-idf approved these changes

2022-09-01 11:33 UTC, merged